apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  ports:
    - name: http
      port: 8080 # Need to be accessed only inside the Cluster
  selector:
    myApp: position-tracker
  type: ClusterIP