apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  ports:
    - name: mongoport
      port: 27017 # Need to be accessed only inside the Cluster
  selector:
    myApp: mongodb
  type: ClusterIP