# How do we want it implemented?
apiVersion : v1
kind : PersistentVolume
metadata :
    name : local-storage
spec :
    storageClassName : mylocalstorage
    accessModes:
        - ReadWriteOnce
    capacity :
        storage : 5Gi
    hostPath :
        path : "/mnt/some/directory/structure/"
        type : DirectoryOrCreate