apiVersion: v1
kind: Pod
metadata:
  name: activemq
  labels:
    myApp: activemq
    myRelease: release1
spec:
  containers:
  - name: activemq-container
    image: richardchesterwood/k8s-fleetman-queue:release1
    ports:
      - containerPort: 8161