apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-api-gateway
spec:
  ports:
    - name: http
      port: 8080 # Need to be accessed only inside the Cluster
  selector:
    myApp: api-gateway
  type: ClusterIP