apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30020
  selector:
    myApp: webapp
  type: NodePort