apiVersion : apps/v1
kind : Deployment
metadata :
 name : position-tracker
spec :
 replicas : 1
 selector :
    matchLabels :
      myApp : position-tracker
 template :
   metadata :
     labels :
        myApp : position-tracker
   spec :
     containers :
     - name : position-tracker
       image : richardchesterwood/k8s-fleetman-position-tracker:release3
       # release2 uses inmemory
       # release3 uses mongodb
       env :
       - name : SPRING_PROFILES_ACTIVE
         value : production-microservice